# Generated by Django 3.2 on 2021-05-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizzeria', '0004_rename_text_comment_pizzacomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pizzacomment',
            field=models.CharField(max_length=50),
        ),
    ]
