# Generated by Django 3.2 on 2021-05-01 14:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Pizzeria', '0006_alter_comment_pizzacomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='imageurl',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
