# Generated by Django 3.2 on 2021-05-01 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pizzeria', '0007_pizza_imageurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='pizzacomment',
            new_name='text',
        ),
    ]
